sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
branches:
  only:
    - master
notifications:
  email:
    - snowyu.lee@gmail.com
