sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
branches:
  only:
    - master
before_install: npm install -g coffee-script
notifications:
  email:
    - snowyu.lee@gmail.com
