// Generated by CoffeeScript 1.9.0
(function() {
  var EventEmitter, Eventable;

  Eventable = require('./eventable');

  module.exports = EventEmitter = (function() {
    function EventEmitter() {}

    return EventEmitter;

  })();

  Eventable(EventEmitter);

  EventEmitter.EventEmitter = EventEmitter;

}).call(this);
